[package]
name = "gh-alert"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sha2 = "0.10"
notify-rust = "4.5"

